package Metthy;

import java.util.ArrayList;
import java.util.Scanner;

/**
 * This class represents a regular coffee truck
 */
public class RegularCoffeeTruck {

    /**
     * The name of the coffee truck.
     */
    protected String name;
    /**
     * The current location of the coffee truck.
     */
    protected String location;

    protected final DrinkManager drinkManager;

    /**
     * List of storage bins.
     */
    protected ArrayList<StorageBin> bins = new ArrayList<>(8);
    /**
     * Log of all sales made by this truck.
     */
    private final ArrayList<String> salesLog;
    /**
     * Total sales revenue generated by the truck.
     */
    private double totalSales;
    /**
     * Scanner object for reading user input from the console.
     */
    private final Scanner scanner = new Scanner(System.in);

    /**
     * Constructs a CoffeeTruck with the given name and location.
     * Initializes 8 storage bins and an empty sales log.
     *
     * @param name     the name of the coffee truck
     * @param location the initial location of the truck
     */
    public RegularCoffeeTruck(String name, String location, DrinkManager drinkManager){

        int i;
        this.name = name;
        this.location = location;
        this.drinkManager = drinkManager;

        //Create the 8 storage bins
        for(i = 1; i <= 8; i++)
            bins.add(new StorageBin(i));

        salesLog = new ArrayList<>();
    }

    /**
     * Displays the current contents of all storage bins in the truck.
     * Empty bins are marked as [Empty].
     */
    public void displayBins(){

        int i, capacity, binNumber;
        double quantity;
        String item;

        System.out.println("--- Storage Bins ---");

        for(i = 0; i < bins.size(); i++){

            StorageBin bin = bins.get(i);
            item = bin.getItemType();
            quantity = bin.getItemQuantity();
            capacity = bin.getCapacity();
            binNumber = i + 1;

            //Bin is empty if no item assigned
            if(item == null)
                System.out.println("Bin #" + binNumber + ": [Empty]");

            else
                System.out.printf("Bin #%d: %s - %.2f / %d\n", binNumber, item, quantity, capacity);
        }
    }

    /**
     * Displays the truck's name, location, storage bin contents,
     * transaction history, and total sales.
     */
    public void displayInfo(){

        int i;
        String truckType;

        if(this instanceof SpecialCoffeeTruck)
            truckType = "Special Truck";
        else
            truckType = "Regular Truck";

        System.out.println("\n[" + truckType + "]");
        System.out.println("Name - " + this.name + " | " + "Location: " + this.location);
        displayBins();
        System.out.println("--- Transactions ---");

        if(getSalesLog().isEmpty())
            System.out.println("No transactions recorded.");

        else{
            for(i = 0; i < getSalesLog().size(); i++){

                String sale = getSalesLog().get(i);
                System.out.println(sale);
            }
        }
        System.out.printf("\nTotal Sales: $%.2f\n", getTotalSales());
    }

    /**
     * Assigns a specific item type and quantity to a given bin number.
     *
     * @param binIndex   the index of the bin (0-based)
     * @param itemType    the type of item to store in the bin
     * @param itemQuantity the quantity of the item to assign
     */
    public void assignItemToBin(int binIndex, String itemType, double itemQuantity){

        bins.get(binIndex).assignItem(itemType, itemQuantity);
    }

    /**
     * Modifies the contents of a specified bin.
     *
     * @param binNumber the 1-based bin number (for display and user selection)
     */
    public void modifyBin(int binNumber){

        int choice, maxCapacity;
        int binIndex = binNumber - 1;
        double quantity;
        boolean invalidQuantity;
        String itemType;

        System.out.println("\nSetting up Bin #" + binNumber);

        StorageBin bin = bins.get(binIndex);

        do{
            invalidQuantity = false;

            System.out.println("Choose item to store in Bin #" + binNumber + ":");
            System.out.println("1. Small Cup");
            System.out.println("2. Medium Cup");
            System.out.println("3. Large Cup");
            System.out.println("4. Coffee Beans");
            System.out.println("5. Milk");
            System.out.println("6. Water");
            System.out.print("Select item number (0 to skip this bin): ");

            choice = scanner.nextInt();
            scanner.nextLine(); //Consume newline

            if(choice == 0){
                System.out.println("Skipping Bin #" + binNumber);
                break;
            }

            else{
                switch(choice){

                    case 1:
                        bin.setItemType("Small Cup");
                        break;
                    case 2:
                        bin.setItemType("Medium Cup");
                        break;
                    case 3:
                        bin.setItemType("Large Cup");
                        break;
                    case 4:
                        bin.setItemType("Coffee Beans");
                        break;
                    case 5:
                        bin.setItemType("Milk");
                        break;
                    case 6:
                        bin.setItemType("Water");
                        break;
                    default:
                        bin.setItemType(null);
                        break;
                }

                if(bin.getItemType() == null)
                    System.out.println("Invalid selection. Please try again.");

                else{
                    maxCapacity = bin.getCapacityForItem(bin.getItemType());
                    System.out.print("Enter quantity (max " + maxCapacity + "): ");
                    quantity = scanner.nextDouble();
                    scanner.nextLine(); //Consume newline

                    if(quantity < 0 || quantity > maxCapacity){

                        System.out.println("Invalid quantity. Must be between 0 and " + maxCapacity + ".");
                        invalidQuantity = true;
                    }

                    else{
                        itemType = bin.getItemType();
                        assignItemToBin(binIndex, itemType, quantity);

                        if(itemType.equalsIgnoreCase("Water") || (itemType.equalsIgnoreCase("Milk")))
                            System.out.println("Bin #" + binNumber + " loaded with " + quantity + " ounces of " + itemType);

                        else if(itemType.equalsIgnoreCase("Coffee Beans"))
                            System.out.println("Bin #" + binNumber + " loaded with " + quantity + " grams of " + itemType);

                        else
                            System.out.println("Bin #" + binNumber + " loaded with " + (int)quantity + " cups ");
                    }
                }
            }
        } while(bin.getItemType() == null || invalidQuantity);
    }

    /**
     * Fills the first 6 bins of a truck with Small Cups, Medium Cups, Large Cups, Coffee Beans, Milk,
     * and Water respectively.
     * Remaining bins are left empty.
     */
    public void setDefaultLoadout(){

        int i;
        double quantity;
        String[] itemTypes = {"Small Cup", "Medium Cup", "Large Cup", "Coffee Beans", "Milk", "Water"};

        for(i = 0; i < bins.size(); i++){

            StorageBin bin = bins.get(i);

            if(i < itemTypes.length){

                String item = itemTypes[i];
                quantity = 1.0 * bin.getCapacityForItem(item);
                bin.assignItem(item, quantity); //Assign to bin
            }

            else{
                //Leave last 2 bins empty
                bin.empty();
            }
        }
    }

    /**
     * Allows user to set up the loadout of a truck.
     */
    public void setLoadout(){

        int i, binNumber;
        String max;
        ArrayList<StorageBin> bins = getBins();

        System.out.println("\n--- Setting Loadout for " + name + " ---");

        System.out.println("Set Storage Bins to default loadout? (yes/no): ");
        max = scanner.nextLine();

        if(max.equalsIgnoreCase("yes"))
            setDefaultLoadout();

        else{
            for(i = 0; i < bins.size(); i++){
                StorageBin bin = bins.get(i);
                binNumber = bin.getBinNumber();

                modifyBin(binNumber);
            }

            System.out.println("\nLoadout for " + name + " complete!\n");
        }
    }

    /**
     * Restocks a specific storage bin.
     *
     * @param binNumber the bin number to restock
     */
    public void restockOneBin(int binNumber){

        double quantity;

        if(binNumber >= 1 && binNumber <= bins.size()){

            StorageBin bin = bins.get(binNumber - 1);
            if(bin.getItemType() == null)
                System.out.println("Bin isn't assigned any item, restock failed");

            else{

                System.out.println("Enter quantity to restock (0 for full restock): ");
                quantity = scanner.nextDouble();

                //Check if bin already full
                if(quantity == 0 && !bins.get(binNumber - 1).isFull()){

                    bins.get(binNumber - 1).fill(); //Fill bin to max capacity
                    System.out.printf("Bin %d restocked to max capacity\n", binNumber);
                }

                else
                    bin.addQuantity(quantity); //Add entered quantity to bin
            }
        }

        else
            System.out.println("Invalid bin number.");
    }

    /**
     * Restocks all bins that have an assigned item.
     *
     */
    public void restockAllBins(){

        int i;
        int flag = 0;

        for(i = 0; i < bins.size() && flag == 0; i++){

            StorageBin bin = bins.get(i);

            if(bin.getItemType() == null)
                flag = 1;
        }

        if(flag == 1)
            System.out.println("Error Restocking. Some bins have no items assigned");

        else{
            System.out.println("Fully restock bins? (yes/no): ");
            String fullRestock = scanner.nextLine();

            if(fullRestock.equalsIgnoreCase("yes")){

                for(i = 0; i < bins.size(); i++){

                    StorageBin bin = bins.get(i);
                    bin.fill();
                }
            }

            else{
                for(i = 0; i < bins.size(); i++){

                    StorageBin bin = bins.get(i);

                    restockOneBin(bin.getBinNumber()); //Restock bin
                }
            }
        }
    }

    /**
     * Allows the user to modify all storage bins.
     * User can choose to set bins to maximum capacity or manually adjust each bin.
     */
    public void modifyAllBins(){

        int i;
        String max;

        System.out.println("Set Storage Bins to default loadout? (yes/no): ");
        max = scanner.nextLine();

        if(max.equalsIgnoreCase("yes"))
            setDefaultLoadout();

        else{
            for(i = 0; i < bins.size(); i++){
                modifyBin(i + 1);
            }
        }
    }

    /**
     * Empties a specific storage bin.
     *
     * @param binNumber the bin number to empty (1-based index)
     */
    public void emptyOneBin(int binNumber){

        if(binNumber >= 1 && binNumber <= bins.size()){

            //Check if bin is already empty
            if(bins.get(binNumber - 1).isEmpty()){
                bins.get(binNumber - 1).empty();
                System.out.println("Bin #" + binNumber + " emptied.");
            }
        }

        else
            System.out.println("Invalid bin number.");
    }

    /**
     * Empties all storage bins.
     */
    public void emptyAllBins(){

        int i;

        for(i = 0; i < bins.size(); i++){

            StorageBin bin = bins.get(i);
            bin.empty(); //Empty bin
        }
        System.out.println("All bins emptied");
    }

    /**
     * Returns the name of a truck.
     *
     * @return the name of the truck
     */
    public String getName(){

        return name;
    }

    /**
     * Returns the current location of a truck.
     *
     * @return the truck location
     */
    public String getLocation(){

        return location;
    }

    /**
     * Sets a truck's name.
     *
     * @param name the new name for the truck
     */
    public void setName(String name){

        this.name = name;
    }

    /**
     * Sets a truck's location.
     *
     * @param location the new location for the truck
     */
    public void setLocation(String location){

        this.location = location;
    }

    /**
     * Displays the truck maintenance menu for a specific coffee truck.
     * <p>Allows the user to:</p>
     * <ul>
     *   <li>Restock bins (either all or individually)</li>
     *   <li>Modify storage bin contents (either all or individually)</li>
     *   <li>Empty bins (either all or individually)</li>
     *   <li>Edit the truck's name or location</li>
     *   <li>Edit global drink ingredient prices</li>
     * </ul>
     *
     */
    public void truckMaintenanceMenu(){

        int option, restock, binNumber;

        do{
            System.out.println("\n=== Truck Maintenance ===");
            System.out.println("1 - Restock Bins (only works on bins with an assigned item)");
            System.out.println("2 - Modify Storage Bin Contents");
            System.out.println("3 - Empty Storage Bins");
            System.out.println("4 - Edit Truck Name");
            System.out.println("5 - Edit Truck Location");
            System.out.println("6 - Edit Pricing (will affect pricing for all trucks)");
            System.out.println("7 - Exit Menu");
            System.out.println("Select an Option: ");
            option = scanner.nextInt();
            scanner.nextLine(); //Absorb new line

            switch(option){

                case 1:
                    System.out.println("1 - Restock all bins");
                    System.out.println("2 - Restock one bin");
                    System.out.println("Select an option: ");
                    restock  = scanner.nextInt();

                    if(restock == 1)
                        restockAllBins(); //Restock all bins

                    else if(restock == 2){
                        System.out.println("Enter Bin Number: ");
                        binNumber = scanner.nextInt();
                        restockOneBin(binNumber); //Restock selected bin
                    }
                    break;
                case 2:
                    System.out.println("1 - Modify all bins");
                    System.out.println("2 - Modify one bin");
                    System.out.println("Select an option: ");
                    int modify = scanner.nextInt();

                    if(modify == 1)
                        modifyAllBins(); //Modify all bins

                    else if(modify == 2){
                        System.out.println("Enter bin number to modify: ");
                        int binNum = scanner.nextInt();

                        modifyBin(binNum); //Modify regular bin
                    }
                    break;
                case 3:
                    System.out.println("1 - Empty all bins");
                    System.out.println("2 - Empty one bin");
                    System.out.println("Select an option: ");
                    int empty = scanner.nextInt();

                    if(empty == 1)
                        emptyAllBins(); //Empty all bins

                    else if(empty == 2){
                        System.out.println("Enter Bin Number: ");
                        binNumber = scanner.nextInt();
                        emptyOneBin(binNumber); //Empty selected bin
                    }
                    break;
                case 4:
                    System.out.println("Enter new name: ");
                    String name = scanner.nextLine();
                    setName(name); //Set new name
                    break;
                case 5:
                    System.out.println("Enter new location: ");
                    String location = scanner.nextLine();
                    setLocation(location); //Set new location
                    break;
                case 6:
                    drinkManager.setIngredientPrices(); //Set ingredient prices
                    break;
                case 7:
                    System.out.println("Exiting Menu...");
                    break;
                default:
                    System.out.println("Invalid option. Please try again");
                    break;
            }
        } while(option != 7);
    }

    /**
     * Returns the list of storage bins associated with a truck.
     *
     * @return an ArrayList of StorageBin objects
     */
    public ArrayList<StorageBin> getBins(){

        return bins;
    }

    /**
     * Finds and returns the first bin that matches the given item name.
     *
     * @param itemName the name of the item to search for
     * @return the matching StorageBin, or null if not found
     */
    public StorageBin findBin(String itemName){

        int i;
        StorageBin result = null;

        bins = getBins();
        String item;

        for(i = 0; i < bins.size(); i++){

            StorageBin bin = bins.get(i);
            item = bin.getItemType();

            if(item != null && item.equalsIgnoreCase(itemName))
                result = bin;
        }

        return result;
    }

    /**
     * Adds a specified amount to the truck's total sales.
     *
     * @param amount the amount to add to total sales
     */
    protected void addToTotalSales(double amount){

        totalSales += amount;
    }

    /**
     * Records a drink sale to a truck's sales log.
     *
     * @param coffeeType the type of coffee sold
     * @param size the size of the drink
     * @param grams the grams of coffee beans used
     * @param milk the ounces of milk used
     * @param water the ounces of water used
     * @param price the price of the drink
     */
    protected void recordSale(String coffeeType, String size, double grams, double milk, double water, double price){

        salesLog.add(String.format("Drink: %s (%s) | %.2f g beans, %.2f oz milk, %.2f oz water | $%.2f",
                coffeeType, size, grams, milk, water, price));
    }

    /**
     * Handles the process of preparing a drink.
     *
     */
    protected void prepareDrink(){

        String coffeeType, coffeeSize, brewType;
        double espressoOz, milkOz, waterOz, espressoGrams, price, ratio;
        double[] ingredients;

        System.out.println("\n--- Prepare Coffee Drink ---");
        coffeeType = drinkManager.selectDrinkType();
        coffeeSize = drinkManager.selectDrinkSize();
        brewType = "Standard";
        ratio = drinkManager.getBrewRatio(brewType);

        if(coffeeType == null || coffeeSize == null)
            System.out.println("Invalid input! Drink preparation cancelled");

        else{
            Drink drink = drinkManager.getDrink(coffeeType, coffeeSize);
            drink.setBrewType(brewType); //All drinks in regular truck are standard brew by default

            System.out.printf("Preparing %s (%s)...\n", coffeeType, coffeeSize);
            drinkManager.showIngredients(coffeeType, coffeeSize, ratio);

            ingredients = drinkManager.getIngredients(coffeeType, coffeeSize, ratio); //Get the ingredients needed for the drink

            StorageBin beanBin = findBin("Coffee Beans"); //Find bin with coffee beans
            StorageBin milkBin = findBin("Milk"); //Find bin with milk
            StorageBin waterBin = findBin("Water"); //Find bin with water
            StorageBin cupBin = findBin(coffeeSize + " Cup"); //Find bin with specified cup size

            //Check if storage bins have sufficient ingredients
            if(drinkManager.hasSufficientIngredients(beanBin, milkBin, waterBin, cupBin, ingredients)){

                espressoOz = ingredients[0];
                milkOz = ingredients[1];
                waterOz = ingredients[2];
                espressoGrams = (espressoOz * 28.34952) / 18.0;
                price = drink.getPrice();

                //Deduct ingredients from storage bins
                drinkManager.useIngredients(beanBin, espressoGrams, milkBin, milkOz, waterBin, waterOz, cupBin);

                System.out.printf("\n>>> Preparing %s Cup...\n", coffeeSize);
                System.out.printf(">>> Brewing Standard espresso - %.2f grams of coffee...\n", espressoGrams);

                if(milkOz > 0)
                    System.out.println(">>> Adding Milk...");

                if(coffeeType.equalsIgnoreCase("Americano"))
                    System.out.println(">>> Adding Water...");

                System.out.printf(">>> %s Done!\n", coffeeType);

                System.out.printf("Total Price: $%.2f\n", price);

                addToTotalSales(price); //Update total sales
                recordSale(coffeeType, coffeeSize, espressoGrams, milkOz, waterOz, price); //Update sales log
            }

            else
                System.out.println("Not enough ingredients or cups. Drink preparation cancelled.");
        }
    }

    /**
     * Displays the main coffee menu for the truck, allowing the user to view
     * available drinks or prepare a new drink.
     *
     */
    public void coffeeMenu(){

        int option;

        do{
            System.out.println("\n=== Coffee Menu ===");
            System.out.println("1 - View Drink Menu");
            System.out.println("2 - Prepare Drink");
            System.out.println("3 - Exit Menu");
            System.out.println("Enter option: ");
            option = scanner.nextInt();

            switch(option){

                case 1:
                    drinkManager.displayDrinksMenu();
                    break;
                case 2:
                    prepareDrink();
                    break;
                case 3:
                    System.out.println("Exiting Menu");
                    break;
                default:
                    System.out.println("Invalid option");
                    break;
            }
        } while(option != 3);
    }

    /**
     * Returns the list of recorded drink sales for the truck.
     *
     * @return an ArrayList of sales log entries
     */
    public ArrayList<String> getSalesLog(){

        return salesLog;
    }

    /**
     * Returns the total sales revenue for the truck.
     *
     * @return the total sales amount
     */
    public double getTotalSales(){

        return totalSales;
    }
}