package Metthy.Model;

import Metthy.Controller.DrinkController;
import Metthy.View.DrinkView;

import java.util.ArrayList;
import java.util.Scanner;

public abstract class CoffeeTruck {

    /**
     * The name of the coffee truck.
     */
    protected String name;
    /**
     * The current location of the coffee truck.
     */
    protected String location;

    protected ArrayList<StorageBin> bins;
    /**
     * Log of all sales made by this truck.
     */
    protected final ArrayList<String> salesLog;
    /**
     * Total sales revenue generated by the truck.
     */
    protected double totalSales;
    /**
     * Scanner object for reading user input from the console.
     */
    protected final Scanner scanner = new Scanner(System.in);

    protected TruckManager truckManager; //Consider removing
    protected DrinkController drinkController;
    protected DrinkView drinkView;

    public CoffeeTruck(String name, String location, TruckManager truckManager, DrinkController drinkController){

        this.name = name;
        this.location = location;
        this.bins = new ArrayList<>();
        this.salesLog = new ArrayList<>();
        this.truckManager = truckManager;
        this.drinkController = drinkController;
        this.drinkView = drinkController.getDrinkView();
    }

    /**
     * Assigns a specific item and quantity to a given bin number.
     *
     * @param bin          the bin to be modified
     * @param content      the type of item to store in the bin
     * @param itemQuantity the quantity of the item to assign
     */
    public void assignItemToBin(StorageBin bin, BinContent content, double itemQuantity){

        bin.setContent(content, itemQuantity);
    }

    /**
     * Fills the first 6 bins of a truck with Small Cups, Medium Cups, Large Cups, Coffee Beans, Milk,
     * and Water respectively.
     * Remaining bins are left empty.
     */
    public void setDefaultLoadout(){

        int i;
        double quantity;
        String[] ingredients = {"Small Cup", "Medium Cup", "Large Cup", "Coffee Bean", "Milk", "Water"};
        BinContent content;

        for(i = 0; i < bins.size(); i++){

            StorageBin bin = bins.get(i);

            if(i < ingredients.length){
                String itemName = ingredients[i];
                content = truckManager.getIngredientFromName(itemName);
                quantity = content.getCapacity();
                assignItemToBin(bin, content, quantity); //Assign to bin
            }

            else
                bin.empty(); //Leave last 2 bins empty
        }
    }



    /**
     * Restocks a specific storage bin.
     *
     * @param bin the bin to restock
     */
    public void restockBin(StorageBin bin, double quantity){

        bin.addQuantity(quantity); //Add entered quantity to bin
    }

    public void fullRestockBin(StorageBin bin){

        bin.fill();
    }

    public void fullRestockAllBins(){

        for(int i = 0; i < bins.size(); i++){
            StorageBin bin = bins.get(i);
            fullRestockBin(bin);
        }
    }

    /**
     * Empties a specific storage bin.
     *
     * @param bin the bin to empty
     */
    public void emptyBin(StorageBin bin){

        bin.empty();
    }

    /**
     * Empties all storage bins.
     */
    public void emptyAllBins(){

        int i;

        for(i = 0; i < bins.size(); i++){

            StorageBin bin = bins.get(i);
            bin.empty(); //Empty bin
        }
    }

    /**
     * Finds and returns the first bin that matches the given item name.
     *
     * @param itemName the name of the item to search for
     * @return the matching StorageBin, or null if not found
     */
    public StorageBin findBin(String itemName){

        int i;
        boolean flag = true;
        StorageBin result = null;

        for(i = 0; i < bins.size() && flag; i++){

            StorageBin bin = bins.get(i);
            BinContent content = bin.getContent();

            if(content != null && content.getName().equalsIgnoreCase(itemName)){
                result = bin;
                flag = false;
            }
        }

        return result;
    }

    /**
     * Adds a specified amount to the truck's total sales.
     *
     * @param amount the amount to add to total sales
     */
    protected void addToTotalSales(double amount){

        totalSales += amount;
    }

    /**
     * Records a drink sale to the truck's sales log.
     *
     * @param coffeeType  the type of coffee sold.
     * @param size        the size of the drink.
     * @param coffeeGrams the grams of coffee beans used.
     * @param milk        the ounces of milk used.
     * @param water       the ounces of water used.
     * @param price       the price of the drink.
     */
    private void recordSale(String coffeeType, String size, double coffeeGrams, double milk, double water, double price){

        String ingredients;
        String addOnText;
        String drinkInfo;

        //Build base ingredient info string (without extra shots or add-ons)
        ingredients = String.format("%.2f g beans, %.2f oz milk, %.2f oz water", coffeeGrams, milk, water);

        //Build formatted drink info line
        drinkInfo = String.format("Drink: %s %s (Standard)", coffeeType, size);

        //No add-ons for regular trucks
        addOnText = "No Add-Ons";

        //Format and add to the sales log
        salesLog.add(String.format("%-30s | %-45s | %s | $%.2f", drinkInfo, ingredients, addOnText, price));
    }

    /**
     * Handles the process of preparing a drink.
     *
     */
    public void prepareDrink(){

        String coffeeType, coffeeSize, brewType;
        double espressoGrams, milkOz, waterOz, price, ratio;
        double[] ingredients;

        drinkView.prepareDrinkHeader();
        coffeeType = drinkView.selectDrinkType();
        coffeeSize = drinkView.selectDrinkSize();
        brewType = "Standard"; //Set brew type to standard by default
        ratio = drinkView.getBrewRatio(brewType);

        Drink drink = drinkController.getDrink(coffeeType, coffeeSize);
        ingredients = drinkController.getAdjustedIngredients(coffeeType, coffeeSize, ratio); //Get the ingredients needed for the drink

        drinkView.showIngredients(coffeeType, coffeeSize, brewType, ingredients); //Show required ingredients

        StorageBin beanBin = findBin("Coffee Bean"); //Find bin with coffee beans
        StorageBin milkBin = findBin("Milk"); //Find bin with milk
        StorageBin waterBin = findBin("Water"); //Find bin with water
        StorageBin cupBin = findBin(coffeeSize + " Cup"); //Find bin with specified cup size
        StorageBin[] bins = { beanBin, milkBin, waterBin, cupBin };

        //Check if storage bins have sufficient ingredients
        if(drinkController.hasSufficientIngredients(bins, ingredients)){

            espressoGrams = ingredients[0];
            milkOz = ingredients[1];
            waterOz = ingredients[2];
            price = drink.getPrice();

            //Deduct ingredients from storage bins
            drinkController.useIngredients(bins, ingredients);

            drinkView.displayPreparationSteps(coffeeType, coffeeSize, "Standard", ingredients);
            drinkView.showTotalPrice(drink.getPrice());

            addToTotalSales(price); //Update total sales
            recordSale(coffeeType, coffeeSize, espressoGrams, milkOz, waterOz, price); //Update sales log
        }

        else
            drinkView.showInsufficientIngredients();
    }

    //GETTERS AND SETTERS

    /**
     * Returns the name of a truck.
     *
     * @return the name of the truck
     */
    public String getName(){

        return name;
    }

    /**
     * Returns the current location of a truck.
     *
     * @return the truck location
     */
    public String getLocation(){

        return location;
    }

    /**
     * Sets a truck's name.
     *
     * @param name the new name for the truck
     */
    public void setName(String name){

        this.name = name;
    }

    /**
     * Sets a truck's location.
     *
     * @param location the new location for the truck
     */
    public void setLocation(String location){

        this.location = location;
    }

    public StorageBin getBinByNumber(int binNumber){

        return bins.get(binNumber - 1);
    }

    /**
     * Returns the list of storage bins associated with a truck.
     *
     * @return an ArrayList of StorageBin objects
     */
    public ArrayList<StorageBin> getBins(){

        return bins;
    }

    /**
     * Returns the list of recorded drink sales for the truck.
     *
     * @return an ArrayList of sales log entries
     */
    public ArrayList<String> getSalesLog(){

        return salesLog;
    }

    /**
     * Returns the total sales revenue for the truck.
     *
     * @return the total sales amount
     */
    public double getTotalSales(){

        return totalSales;
    }

    @Override
    public String toString() {

        return name + " (" + location + ")";
    }
}
